In [1]:
import pandas as pd
import pyodbc

conn = pyodbc.connect(
    "DRIVER={SQL Server};"
    "SERVER=localhost\\SQLEXPRESS;"
    "DATABASE=AdventureWorks2025;"
    "Trusted_Connection=yes;"
)

query = """
SELECT TOP 1000 *
FROM Sales.SalesOrderHeader
"""

df = pd.read_sql(query, conn)
df.head()

C:\Users\hisuk\AppData\Local\Temp\ipykernel_21648\3690694528.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,SalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,OnlineOrderFlag,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,...,CreditCardID,CreditCardApprovalCode,CurrencyRateID,SubTotal,TaxAmt,Freight,TotalDue,Comment,rowguid,ModifiedDate
0,43659,10,2022-05-30,2022-06-11,2022-06-06,5,False,SO43659,PO522145787,10-4020-000676,...,16281.0,105041Vi84182,NaN,20565.6206,1971.5149,616.0984,23153.2339,None,79B65321-39CA-4115-9CBA-8FE0903E12E6,2022-06-06
1,43660,10,2022-05-30,2022-06-11,2022-06-06,5,False,SO43660,PO18850127500,10-4020-000117,...,5618.0,115213Vi29411,NaN,1294.2529,124.2483,38.8276,1457.3288,None,738DC42D-D03B-48A1-9822-F95A67EA7389,2022-06-06
2,43661,10,2022-05-30,2022-06-11,2022-06-06,5,False,SO43661,PO18473189620,10-4020-000442,...,1346.0,85274Vi6854,4.0,32726.4786,3153.7696,985.5530,36865.8012,None,D91B9131-18A4-4A11-BC3A-90B6F53E9D74,2022-06-06
3,43662,10,2022-05-30,2022-06-11,2022-06-06,5,False,SO43662,PO18444174044,10-4020-000227,...,10456.0,125295Vi53935,4.0,28832.5289,2775.1646,867.2389,32474.9324,None,4A1ECFC0-CC3A-4740-B028-1C50BB48711C,2022-06-06
4,43663,10,2022-05-30,2022-06-11,2022-06-06,5,False,SO43663,PO18009186470,10-4020-000510,...,4322.0,45303Vi22691,NaN,419.4589,40.2681,12.5838,472.3108,None,9B1E7A40-6AE0-4AD3-811C-A64951857C4B,2022-06-06

In [3]:
query = """
SELECT
    h.SalesOrderID,
    h.OrderDate,
    h.CustomerID,
    d.ProductID,
    d.OrderQty,
    d.UnitPrice,
    d.LineTotal
FROM Sales.SalesOrderHeader h
JOIN Sales.SalesOrderDetail d
ON h.SalesOrderID = d.SalesOrderID
"""

df = pd.read_sql(query, conn)

C:\Users\hisuk\AppData\Local\Temp\ipykernel_21648\2927779272.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [4]:
df.describe()

,SalesOrderID,OrderDate,CustomerID,ProductID,OrderQty,UnitPrice,LineTotal
count,121317.000000,121317,121317.000000,121317.000000,121317.000000,121317.000000,121317.000000
mean,57827.363782,2024-07-14 19:44:52.321768448,24345.630505,841.680836,2.266080,465.093496,905.449207
min,43659.000000,2022-05-30 00:00:00,11000.000000,707.000000,1.000000,1.328200,1.374000
25%,49884.000000,2024-02-28 00:00:00,18177.000000,768.000000,1.000000,21.490000,24.990000
50%,57029.000000,2024-09-29 00:00:00,29485.000000,863.000000,1.000000,49.990000,134.982000
75%,65490.000000,2025-01-30 00:00:00,29795.000000,921.000000,3.000000,602.346000,1120.490000
max,75123.000000,2025-06-29 00:00:00,30118.000000,999.000000,44.000000,3578.270000,27893.619000
std,9009.147902,NaN,6689.110387,86.452124,2.491323,751.885081,1693.417389

In [7]:
df["Revenue"] = df["LineTotal"]

In [8]:
df.groupby("ProductID")["Revenue"].sum().sort_values(ascending=False).head()

ProductID
782    4.400593e+06
783    4.009495e+06
779    3.693678e+06
780    3.438479e+06
781    3.434257e+06
Name: Revenue, dtype: float64

In [9]:
df.groupby("ProductID")["Revenue"].sum().sort_values(ascending=False).head(10)

ProductID
782    4.400593e+06
783    4.009495e+06
779    3.693678e+06
780    3.438479e+06
781    3.434257e+06
784    3.309673e+06
793    2.516857e+06
794    2.347656e+06
795    2.012448e+06
753    1.847819e+06
Name: Revenue, dtype: float64

In [10]:
df.groupby("ProductID")["OrderQty"].sum().sort_values(ascending=False).head(10)

ProductID
712    8311
870    6815
711    6743
715    6592
708    6532
707    6266
864    4247
873    3865
884    3864
714    3636
Name: OrderQty, dtype: int64

In [11]:
df.groupby(df["OrderDate"].dt.to_period("M"))["Revenue"].sum()

OrderDate
2022-05    5.177374e+05
2022-06    2.001279e+06
2022-07    1.668510e+06
2022-08    1.326138e+06
2022-09    2.836410e+06
2022-10    2.269438e+06
2022-11    1.437343e+06
2022-12    2.504196e+06
2023-01    2.076792e+06
2023-02    1.449883e+06
2023-03    2.975748e+06
2023-04    1.634601e+06
2023-05    3.074603e+06
2023-06    4.099354e+06
2023-07    3.417954e+06
2023-08    2.175637e+06
2023-09    3.454152e+06
2023-10    2.544091e+06
2023-11    1.872702e+06
2023-12    2.829405e+06
2024-01    2.087872e+06
2024-02    2.343260e+06
2024-03    3.407037e+06
2024-04    2.533057e+06
2024-05    3.258341e+06
2024-06    5.063798e+06
2024-07    4.918580e+06
2024-08    3.325296e+06
2024-09    4.539829e+06
2024-10    4.820725e+06
2024-11    3.291238e+06
2024-12    4.082854e+06
2025-01    4.276428e+06
2025-02    3.565879e+06
2025-03    4.987902e+06
2025-04    5.222759e+06
2025-05    1.908059e+06
2025-06    4.749155e+04
Freq: M, Name: Revenue, dtype: float64